// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FamousQuotes.Models
{
    public partial class Quotes
    {
        public Quotes()
        {
            QuotesAuthors = new HashSet<QuotesAuthors>();
            UsersQuzi = new HashSet<UsersQuzi>();
        }

        [Key]
        public long IdQuotes { get; set; }
        [StringLength(350)]
        public string Header { get; set; }
        [Required]
        public string QuoteText { get; set; }
        [Required]
        [StringLength(250)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ModifyDate { get; set; }

        [InverseProperty("IdQuotesNavigation")]
        public virtual ICollection<QuotesAuthors> QuotesAuthors { get; set; }
        [InverseProperty("IdQuotesNavigation")]
        public virtual ICollection<UsersQuzi> UsersQuzi { get; set; }
    }
}