// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FamousQuotes.Models
{
    public partial class UsersSession
    {
        [Key]
        public long IdUsersSession { get; set; }
        public long IdUsers { get; set; }
        [Required]
        [StringLength(500)]
        public string Token { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime LoginTime { get; set; }

        [ForeignKey(nameof(IdUsers))]
        [InverseProperty(nameof(Users.UsersSession))]
        public virtual Users IdUsersNavigation { get; set; }
    }
}