// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FamousQuotes.Models
{
    public partial class UsersQuzi
    {
        [Key]
        public long IdUsersQuzi { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public long IdUsers { get; set; }
        public long IdQuotes { get; set; }
        public long IdQuotesAuthors { get; set; }
        public bool WasCorrect { get; set; }

        [ForeignKey(nameof(IdQuotesAuthors))]
        [InverseProperty(nameof(QuotesAuthors.UsersQuzi))]
        public virtual QuotesAuthors IdQuotesAuthorsNavigation { get; set; }
        [ForeignKey(nameof(IdQuotes))]
        [InverseProperty(nameof(Quotes.UsersQuzi))]
        public virtual Quotes IdQuotesNavigation { get; set; }
        [ForeignKey(nameof(IdUsers))]
        [InverseProperty(nameof(Users.UsersQuzi))]
        public virtual Users IdUsersNavigation { get; set; }
    }
}