// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FamousQuotes.Models
{
    public partial class Users
    {
        public Users()
        {
            UsersQuzi = new HashSet<UsersQuzi>();
            UsersSession = new HashSet<UsersSession>();
            UsersSettings = new HashSet<UsersSettings>();
        }

        [Key]
        public long IdUsers { get; set; }
        [Required]
        [StringLength(150)]
        public string Email { get; set; }
        [Required]
        [StringLength(250)]
        public string DisplayName { get; set; }
        [Required]
        [StringLength(500)]
        public string PasswordHash { get; set; }
        [Required]
        [StringLength(500)]
        public string PasswordSalt { get; set; }
        [Required]
        public bool? IsEnabled { get; set; }
        [Required]
        public bool? IsAdmin { get; set; }

        [InverseProperty("IdUsersNavigation")]
        public virtual ICollection<UsersQuzi> UsersQuzi { get; set; }
        [InverseProperty("IdUsersNavigation")]
        public virtual ICollection<UsersSession> UsersSession { get; set; }
        [InverseProperty("IdUsersNavigation")]
        public virtual ICollection<UsersSettings> UsersSettings { get; set; }
    }
}