CREATE TABLE Users(
	IdUsers BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Email NVARCHAR(150) NOT NULL,
	DisplayName NVARCHAR(250) NOT NULL,
	PasswordHash NVARCHAR(500) NOT NULL,
	PasswordSalt NVARCHAR(500) NOT NULL,
	IsEnabled BIT NOT NULL DEFAULT 1
)

CREATE TABLE Quotes(
	IdQuotes BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Header NVARCHAR(350) NULL,
	QuoteText NVARCHAR(MAX) NOT NULL,
	CreatedBy NVARCHAR(250) NOT NULL,
	CreateDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifyDate DATE NULL,
)

CREATE TABLE Authors(
	IdAuthors BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	AuthorName NVARCHAR(250) NOT NULL
)

CREATE TABLE QuotesAuthors(
	IdQuotesAuthors BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdQuotes BIGINT NOT NULL FOREIGN KEY(IdQuotes) REFERENCES dbo.Quotes(IdQuotes) ON DELETE CASCADE,
	AuthorName NVARCHAR(250) NOT NULL,
	IsCorrectAnswer BIT NOT NULL DEFAULT 0
)

CREATE TABLE UsersQuzi(
	IdUsersQuzi BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Date DATE NOT NULL DEFAULT GETDATE(),
	StartTime TIME NULL,
	EndTime TIME NULL,
	IdUsers BIGINT NOT NULL FOREIGN KEY(IdUsers) REFERENCES dbo.Users(IdUsers) ON DELETE CASCADE,
	IdQuotes BIGINT NOT NULL FOREIGN KEY(IdQuotes) REFERENCES dbo.Quotes(IdQuotes) ON DELETE CASCADE,
	IdQuotesAuthors BIGINT NOT NULL FOREIGN KEY(IdQuotesAuthors) REFERENCES dbo.QuotesAuthors(IdQuotesAuthors),
	WasCorrect BIT NOT NULL 
)

CREATE TABLE UsersSettings(
	IdUsersSettings BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdUsers BIGINT NOT NULL FOREIGN KEY(IdUsers) REFERENCES dbo.Users(IdUsers) ON DELETE CASCADE,
	SimpleQuizMode BIT NOT NULL DEFAULT 1
)

CREATE TABLE UsersSesions(
	IdUsersSesions BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IdUsers BIGINT NOT NULL FOREIGN KEY(IdUsers) REFERENCES dbo.Users(IdUsers),
	Token NVARCHAR(500) NOT NULL,
	LoginTime DATETIME NOT NULL DEFAULT GETDATE()
)